<template>
  <div>
    <div class="text-h5" style="
    position: fixed;background: white; padding: 10px 0;
    width: calc(100vw - 69px);
">
      <div class="px-2 d-flex">
        Colaboradores
        <v-spacer></v-spacer>
        <v-btn text color="success" depressed small>
          <v-icon left>mdi-file-excel</v-icon> Excel
        </v-btn>
        <v-btn class="ml-1" text color="primary" depressed small>
          <v-icon left>mdi-file</v-icon> csv
        </v-btn>
        <v-btn color="" icon><v-icon>mdi-bell</v-icon></v-btn>
      </div> 
      <div class="px-2">
        <v-tabs v-model="tabs">
          <v-tab href="#tabela">
            Colaboradores
          </v-tab>
          <v-tab href="#importar">
            Importar
          </v-tab>
        </v-tabs>
      </div>
    </div>
    <div style="padding-top: 95px; height: calc(100vh - 50px); overflow: auto" class="px-2">
      <v-fade-transition>
        <table v-if="tabs == 'tabela'" style="width: 1000px;">
          <thead>
            <tr>
              <th class="text-start white" style="    position: sticky;
      top: 3px;">Title 1</th>
              <th class="text-start white" style="    position: sticky;
      top: 3px;">Title 1</th>
              <th class="text-start white" style="    position: sticky;
      top: 3px;">Title 1</th>
              <th class="text-start white" style="    position: sticky;
      top: 3px;">Title 1</th>
              <th class="text-start white" style="    position: sticky;
      top: 3px;">Title 1</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
            <tr>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
              <td>asdjuashiah</td>
            </tr>
          </tbody>
        </table>
        <v-col cols="12" v-if="tabs == 'importar'">oaidsjasiojoiasjiaoisd</v-col>
      </v-fade-transition>
      
    </div>
    <div class="py-2 white d-flex w-100 " style="position: fixed;width: calc(100vw - 69px);">
      <div class="d-flex px-2" style="width: calc(100vw - 69px);">
        <v-spacer></v-spacer>
        <v-pagination v-model="page" :length="6"></v-pagination>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'HelloWorld',

    data: () => ({
      page: 1,
      tabs: 'tabela'
    }),
  }
</script>
